fix

diff --git a/bin/dmgr b/bin/dmgr
--- a/bin/dmgr
+++ b/bin/dmgr
@@ -72,6 +72,8 @@ function _hook() {
       sed "s/^RUN$/r/" |
       sed "s/^LINK$/l/" |
       sed "s/^UNLINK$/u/" |
+      sed "s/^USE$/s/" |
+      sed "s/^UNUSE$/n/" |
       sed "s/^REARCH$/c/")
   done
 
@@ -99,6 +101,10 @@ function _hook() {
         eval $(echo $line | sed "s/^LINK/_link/")
       elif [[ $line =~ "^UNLINK\s" ]] && [[ $ac =~ "a|u" ]]; then
         eval $(echo $line | sed "s/^UNLINK/_unlink/")
+      elif [[ $line =~ "^USE" ]] && [[ $ac =~ "a|s" ]]; then
+        eval $(echo $line | sed "s/^USE/_use/")
+      elif [[ $line =~ "^UNUSE" ]] && [[ $ac =~ "a|n" ]]; then
+        eval $(echo $line | sed "s/^UNUSE/_unuse/")
       fi
     fi
   done
@@ -160,6 +166,33 @@ function _unlink() {
   return 0
 }
 
+function _use() {
+  local e=
+
+  for e in $(echo $@ | tr -s ',' ' '); do
+    if [ ! -e $DMGR_REPODIR/bin/$e ]; then
+      echo "${e} is not found."
+      continue
+    else
+      [ ! -e $HOME/bin ] && mkdir -v $HOME/bin
+      ln -s $DMGR_REPODIR/bin/$e $HOME/bin/$e
+    fi
+  done
+}
+
+function _unuse() {
+  local e=
+
+  for e in $(echo $@ | tr -s ',' ' '); do
+    if [ ! -e $HOME/bin/$e ]; then
+      echo "${e} is not found."
+      continue
+    else
+      rm -f $HOME/bin/$e
+    fi
+  done
+}
+
 #
 # Report an error and exit with error status.
 # @param $1 An error message.
@@ -201,7 +234,7 @@ function _exist() {
 }
 
 function _enforce_arg_chk() {
-  if ! eval "[ $(($1 - 1)) $(echo $2 | sed 's/>=/-ge/') ${3} ]"; then
+  if ! eval "[ $(($1 - 1)) $(echo $2 | sed 's/>=/-ge/' | sed 's/=/-eq/') ${3} ]"; then
     echo "Missing arguments."
     return 1
   fi
@@ -214,6 +247,18 @@ function _enforce_arg_chk() {
 #
 function def() {
   DMGR_CONFPATH=(${@:1} $DMGR_CONFPATH)
+}
+
+function dmgr_env() {
+  case $1 in
+    "repo") echo $DMGR_REPODIR;;
+    "plugins") echo $DMGR_PLUGINDIR;;
+    *)
+      echo "Choose from 'repo', 'plugins'"
+      exit 1;;
+  esac
+
+  exit 0
 }
 
 #
@@ -238,33 +283,6 @@ function dmgr_deals() {
 #
 function dmgr_installed() {
   _exist $DMGR_PLUGIN $1; exit $?
-}
-
-#
-# Show help message.
-#
-function dmgr_help() {
-  cat <<_EOF_
-dmgr v${DMGR_VERSION}
-
-Usage
-
-  dmgr <command> (<options>)
-
-Options
-  has       : Check if features are enabled.
-  deals     : Check if features are supported.
-  support   : Support new features.
-  unsupport : Remove features from support list.
-  edit      : Edit a configuration file. The file path is defined in <DMGR_CONFPATH>/core/paths/*.
-  enable    : Enable features. The feature must be supported by dmgr.
-  disable   : Disable features. The feature must be supported by dmgr.
-  update    : Update dmgr and the features.
-  list      : List supported features.
-  help      : Show help message.
-_EOF_
-
-  exit 0
 }
 
 #
@@ -389,13 +407,13 @@ function dmgr_update() {
 
   _fbold "\n:: Updating dotfiles..."
 
-  if [ $# = 1 ]; then
-    inuse=($(_parse $DMGR_INUSE))
-  else
+  if [ $# -ge 1 ]; then
     inuse=$@
+  else
+    inuse=($(_parse $DMGR_INUSE))
   fi
 
-  for e in $@; do
+  for e in $inuse; do
     if ! _exist $DMGR_SUPPORT $e; then
       echo "${e} is not supported. To support this feature, use 'dmgr support <feature_name>'"
       continue
@@ -457,7 +475,7 @@ function dmgr_edit() {
 }
 
 function dmgr_install() {
-  local official= ctr= item= e= d=
+  local official= ctr= item= e= this=
 
   _fbold "\n:: Installing plugins..."
   official=($(_parse $DMGR_OFFICIAL))
@@ -467,9 +485,15 @@ function dmgr_install() {
       ctr=($(echo $item | tr -s '=' ' '))
 
       if [[ ${ctr[1]} == $e ]]; then
-        d=$DMGR_PLUGINDIR/${ctr[1]}
-        git clone ${ctr[2]} $d
-        [ -e $d/dmgr-setup.sh ] && $(. $d/dmgr-setup.sh && install)
+        this=$DMGR_PLUGINDIR/${ctr[1]}
+
+        if [ -e $this ]; then
+          echo "${e} has already installed. Re-install the plugin."
+        else
+          git clone ${ctr[2]} $this
+        fi
+
+        [ -e $this/dmgr-setup ] && . $this/dmgr-setup && install
 
         _save $DMGR_PLUGIN $plugins $e
         echo "$e has been installed."
@@ -481,7 +505,7 @@ function dmgr_install() {
 }
 
 function dmgr_uninstall() {
-  local plugins= e=
+  local plugins= e= this=
 
   _fbold "\n:: Uninstalling plugins..."
 
@@ -491,13 +515,43 @@ function dmgr_uninstall() {
       exit 1
     fi
 
-    d=$DMGR_PLUGINDIR/$e
-    [ -e $d/dmgr-setup.sh ] && $(. $d/dmgr-setup.sh && uninstall)
-    rm -rf $d
+    this=$DMGR_PLUGINDIR/$e
+    [ -e $this/dmgr-setup ] && . $this/dmgr-setup && uninstall
+    rm -rf $this
 
     _save $DMGR_PLUGIN ${$(_parse $DMGR_PLUGIN)[@]/#%($e)}
     echo "$e has been removed."
   done
+
+  exit 0
+}
+
+#
+# Show help message.
+#
+function dmgr_help() {
+  cat <<_EOF_
+dmgr v${DMGR_VERSION}
+
+Usage
+
+  dmgr <command> (<options>)
+
+Options
+  has       : Check if a feature is enabled.
+  deals     : Check if a feature is supported.
+  installed : Check if a plugin is installed.
+  support   : Support new features.
+  unsupport : Remove features from support list.
+  install   : Install plugins.
+  uninstall : Uninstall plugins.
+  edit      : Edit a configuration file. The file path is defined in <DMGR_CONFPATH>/core/paths/*.
+  enable    : Enable features. The feature must be supported by dmgr.
+  disable   : Disable features. The feature must be supported by dmgr.
+  update    : Update dmgr and the features.
+  list      : List supported features.
+  help      : Show help message.
+_EOF_
 
   exit 0
 }
@@ -528,12 +582,13 @@ case $1 in
   "installed")  _enforce_arg_chk $# '=' 1 && dmgr_installed $2 ;;
   "support")    _enforce_arg_chk $# '=' 1 && dmgr_support $2 ;;
   "unsupport")  _enforce_arg_chk $# '=' 1 && dmgr_unsupport $2 ;;
-  "edit")       _enforce_arg_chk $# '=' 1 && dmgr_edit $2 ;;
-  "enable")     _enforce_arg_chk $# '>=' 2 && dmgr_enable ${@:2} ;;
-  "disable")    _enforce_arg_chk $# '>=' 2 && dmgr_disable ${@:2} ;;
-  "install")    _enforce_arg_chk $# '>=' 2 && dmgr_install ${@:2};;
-  "uninstall")  _enforce_arg_chk $# '>=' 2 && dmgr_uninstall ${@:2} ;;
+  "env")        _enforce_arg_chk $# '>=' 1 && dmgr_env $2 ;;
+  "enable")     _enforce_arg_chk $# '>=' 1 && dmgr_enable ${@:2} ;;
+  "disable")    _enforce_arg_chk $# '>=' 1 && dmgr_disable ${@:2} ;;
+  "install")    _enforce_arg_chk $# '>=' 1 && dmgr_install ${@:2};;
+  "uninstall")  _enforce_arg_chk $# '>=' 1 && dmgr_uninstall ${@:2} ;;
   "update")     dmgr_update ${@:2} ;;
+  "edit")       dmgr_edit $2 ;;
   "list")       dmgr_list ;;
   "help")       dmgr_help ;;
 esac
